config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    delete 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  scope constraints: ->(req) { MultiTenant::FetchTenant.call(req) == 'tldr' } do
    root to: 'tldr_main#index', as: :tldr_main_root
  end

  scope constraints: ->(req) { MultiTenant::FetchTenant.call(req) == 'peggedplacetowork' } do
    root to: 'pegged_place_to_works#index', as: :peggedplacetowork_root

    get 'great_vs_pegged_place_to_work', to: 'great_place_to_works#index'

    resources :change_requests, only: %i[new create]
  end

  scope constraints: ->(req) { MultiTenant::FetchTenant.call(req) == 'techsalary' } do
    root to: 'salaries#index', as: :techsalary_root

    resources :salaries, only: %i[new create] do
      member do
        post 'vote_accurate'
        post 'vote_fake'
      end

      collection do
        get 'all'
      end
    end
  end

  scope constraints: ->(req) { MultiTenant::FetchTenant.call(req) == 'thetax' } do
    root to: 'thetax#index', as: :thetax_root

    post 'tax_calculate', to: 'thetax#calculate'
  end

  get '*path' => redirect('/') unless Rails.env.development?
end

app/views/layouts/techsalary/_footer.html.erb
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 border-top">
    <h6 class="pt-3">
      We value your privacy on salary submissions & voting. So we only store SHA512 hashed email address in the database for voting and we do not connect salary submissions to user accounts.
    </h6>
    <p class="col-md-4 mb-0">
      Want to contribute?
      <%= link_to 'Check here', "https://github.com/dilumn/tldr", target: '_blank' %>
      <%= link_to image_tag("github-logo.png", width: 30), "https://github.com/dilumn/tldr", target: '_blank' %>
    </p>
  </footer>
</div>

app/views/layouts/techsalary/_nav_bar.html.erb
<div class="container">
  <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
      <%= image_tag("techsalary/logo.png", width: 80) %>
      <h3 class="ms-3">Community driven Sri Lankan tech salary database</h3>
    </a>

    <ul class="nav nav-pills">
      <% if current_page?(techsalary_root_path) %>
        <li class="nav-item"><a href="/" class="nav-link active" aria-current="page">Home</a></li>
      <% else %>
        <li class="nav-item"><a href="/" class="nav-link" aria-current="page">Home</a></li>
      <% end %>

      <div>
        <%= link_to 'Add your salary', new_salary_path, class: "ms-1 me-2 btn btn-warning" %>
        <% if current_user %>
          <%= link_to "Logout", destroy_user_session_path, data: { "turbo-method": :delete }, class: "btn btn-danger" %>
        <% end %>
        <%= link_to image_tag("github-logo.png", width: 40), "https://github.com/dilumn/tldr", target: '_blank' %>
      </div>
    </ul>

  </header>
</div>

app/views/layouts/techsalary/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechSalary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= favicon_link_tag asset_path('techsalary/favicon.png') %>

    <%= analytics_init if GoogleAnalytics.valid_tracker? %>
  </head>

  <body>
    <%= render "layouts/flash" %>

    <%= render "layouts/techsalary/nav_bar" %>
    <%= yield %>
    <%= render "layouts/techsalary/footer" %>
  </body>
</html>