config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    delete 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  scope constraints: ->(req) { MultiTenant::FetchTenant.call(req) == 'tldr' } do
    root to: 'tldr_main#index', as: :tldr_main_root
  end

  scope constraints: ->(req) { MultiTenant::FetchTenant.call(req) == 'peggedplacetowork' } do
    root to: 'pegged_place_to_works#index', as: :peggedplacetowork_root

    get 'great_vs_pegged_place_to_work', to: 'great_place_to_works#index'

    resources :change_requests, only: %i[new create]
  end

  scope constraints: ->(req) { MultiTenant::FetchTenant.call(req) == 'techsalary' } do
    root to: 'salaries#index', as: :techsalary_root

    resources :salaries, only: %i[new create] do
      member do
        post 'vote_accurate'
        post 'vote_fake'
      end

      collection do
        get 'all'
      end
    end
  end

  scope constraints: ->(req) { MultiTenant::FetchTenant.call(req) == 'thetax' } do
    root to: 'thetax#index', as: :thetax_root

    post 'tax_calculate', to: 'thetax#calculate'
  end

  get '*path' => redirect('/') unless Rails.env.development?
end

app/models/salary.rb
# frozen_string_literal: true

class Salary < ApplicationRecord
  include DesignationEnum
  include TechnologyEnum
  include CurrencyEnum

  enum currency: CURRENCIES

  enum education: {
    bachelors_degree: 'Bachelors Degree',
    diploma: 'Diploma',
    higher_diploma: 'Higher Diploma',
    masters: 'Masters',
    phd: 'PhD'
  }

  enum company_size: {
    below_10: 'Below 10',
    '10_to_20': '10 to 20',
    '20_to_50': '20 to 50',
    '50_to_100': '50 to 100',
    '100_to_500': '100 to 500',
    more_than_500: 'More than 500'
  }

  enum status: {
    approved: 'approved',
    rejected: 'rejected'
  }

  has_many :salary_votes, dependent: :destroy

  def accurate_votes_count
    salary_votes.count(&:accurate?)
  end

  def fake_votes_count
    salary_votes.count(&:fake?)
  end

  def salary_details
    text = ''

    text += "#{salary_amount_text}<br>"
    text += "<b>Year</b> - #{year}<br>"
    text += "<b>Work experience</b> - #{work_experience} year/s<br>"
    text += "<b>Education</b> - #{Salary.educations[education]}<br>" if education.present?
    text += "<b>Company size</b> - #{Salary.company_sizes[company_size]}<br>" if company_size.present?
    text += "<b>Designation</b> - #{Salary.designations[designation]}<br>" if designation.present?
    if primary_technology.present?
      text += "<b>Primary Technology</b> - #{Salary.primary_technologies[primary_technology]}<br>"
    end
    text += '<b>Pegged to foreign currency?</b> - Yes <br>' if pegged_salary.present?
    text += '<b>Company has a legal entity in Sri Lanka?</b> - No <br>' if company_base_lk == false

    text += '<br>' if advice.present?

    text += "<b>Advice for a junior to achieve your salary or even more</b> - #{advice} <br>" if advice.present?

    text
  end

  def salary_amount_text
    amount_text = "<b>Amount</b> - #{amount.to_fs(:delimited)} #{currency}"

    return amount_text if currency == 'LKR'

    "#{amount_text}, (Approximately - #{salary_amount_lkr.to_fs(:delimited)} LKR)"
  end

  def salary_amount_lkr
    Money.from_amount(amount, currency).exchange_to('LKR').to_i
  end
end

app/controllers/salaries_controller.rb
# frozen_string_literal: true

class SalariesController < ApplicationController
  before_action :authenticate_user!, only: %i[vote_accurate vote_fake]

  def index
    salaries = Salary.includes(:salary_votes).where(status: 'approved').group_by(&:designation)
    @grouped_salaries = salaries.sort_by do |_key, value|
      -value.size
    end.to_h
  end

  def all
    @q = Salary.includes(:salary_votes).where(status: 'approved').order(id: :desc).ransack(params[:q])
    @salaries = @q.result.page(params[:page])
  end

  def new
    @salary = Salary.new
  end

  def create
    salary = Salary.new(permitted_params)

    if salary.save
      flash[:success] = 'Salary added.'
      redirect_to all_salaries_path
    else
      flash[:error] = salary.errors.full_messages.join(', ')
      redirect_to new_salary_path
    end
  end

  def vote_accurate
    add_vote(:accurate)
  end

  def vote_fake
    add_vote(:fake)
  end

  private

  def permitted_params
    params.require(:salary).permit!
  end

  def selected_salary
    @selected_salary ||= Salary.find_by(id: params[:id])
  end

  def add_vote(vote_type)
    if vote(vote_type).persisted?
      flash[:success] = 'Thank you for the vote.'
    else
      flash[:error] = 'You have already voted for this salary. Cannot vote twice'
    end
    redirect_to techsalary_root_path
  end

  def vote(vote_type)
    SalaryVote.create(user: current_user, salary: selected_salary, vote_type:)
  end
end

app/views/salaries/all.html.erb
<div class="container">

  <%= search_form_for @q, url: all_salaries_path, class: 'row pb-3' do |f| %>
    <p>
      Filter by:
    </p>
    <div class="row">
      <div class="col-6 col-md-3">
        <%= f.number_field :amount_gteq, placeholder: 'Salary above', class: "form-control" %>
      </div>
      <div class="col-6 col-md-3">
        <%= f.select :currency_eq, Salary.currencies.to_a, { include_blank: 'Currency' }, class: "form-control" %>
      </div>
      <div class="col-6 col-md-3">
        <%= f.select :year_eq, ((Date.today.year - 20)..Date.today.year).to_a.reverse, { include_blank: 'Salary year' }, class: "form-control" %>
      </div>
      <div class="col-6 col-md-3">
        <%= f.select :work_experience_eq, (0..30).to_a, { include_blank: 'Work experience' }, class: "form-control" %>
      </div>
    </div>
    <div class="row mt-1">
      <div class="col-6 col-md-3">
        <%= f.select :education_eq, Salary.educations.map{ |education| [education[1], education[0]] }, { include_blank: 'Education'}, class: "form-control" %>
      </div>
      <div class="col-6 col-md-3">
        <%= f.select :company_size_eq, Salary.company_sizes.map{ |size| [size[1], size[0]] }, { include_blank: 'Company size'}, class: "form-control" %>
      </div>
      <div class="col-6 col-md-3">
        <%= f.select :designation_eq, Salary.designations.map{ |designation| [designation[1], designation[0]] }, { include_blank: 'Designation'}, class: "form-control" %>
      </div>
      <div class="col-6 col-md-3">
        <%= f.select :primary_technology_eq, Salary.primary_technologies.map{ |technology| [technology[1], technology[0]] }, { include_blank: 'Technology'}, class: "form-control" %>
      </div>
    </div>
    <div class="row mt-1">
      <div class="col-6 col-md-1">
        <%= f.submit 'Search', class: 'btn btn-primary' %>
      </div>
      <div class="col-6 col-md-2">
        <%= link_to "Clear Search", request.path, class: 'btn btn-warning' %>
      </div>
    </div>
  <% end %>

  <div class="mb-1 text-end">
    <%= page_entries_info @salaries, entry_name: 'salary' %>
  </div>

  <div class="d-flex mb-1 justify-content-end">
    <%= paginate @salaries %>
  </div>

  <div class="row justify-content-center">
    <div class="col-8 col-md-8 grid-header-col">Salary details</div>
    <div class="col-4 col-md-4 grid-header-col">Accuracy Votes</div>
  </div>

  <% @salaries.each do |salary| %>
    <div class="row justify-content-center">
      <div class="col-8 col-md-8 grid-content-col"><%= salary.salary_details.html_safe %></div>
      <div class="col-4 col-md-4 grid-content-col">
        <div class="row ms-1 fw-bold">
          <%= salary.accurate_votes_count %> voted as accurate
        </div>
        <div class="row ms-1 mb-4 fw-bold">
          <%= salary.fake_votes_count %> voted as possible fake
        </div>

        <% if current_user %>
          <div class="row">
            <p>
              What do you think? Vote here.
            </p>
            <div class="col-12 col-md-6 pb-1">
              <%= button_to "Accurate", vote_accurate_salary_path(salary), method: :post, class: "form-control btn btn-primary" %>
            </div>
            <div class="col-12 col-md-6">
              <%= button_to "Fake", vote_fake_salary_path(salary), method: :post, class: "form-control btn btn-danger" %>
            </div>
          </div>
        <% else %>
          <div class="row">
            <%= button_to "Login with Google to vote", user_google_oauth2_omniauth_authorize_path, method: :post, 'data-turbo': false, class: "form-control" %>
          </div>
        <% end %>

      </div>
    </div>
  <% end %>

  <div class="d-flex justify-content-end mt-1">
    <%= paginate @salaries %>
  </div>
</div>

app/views/salaries/index.html.erb
<div class="container">

  <div class="row">
    <div class="col-6 col-md-2">
      <%= link_to "Salary full list here", all_salaries_path, class: '' %>
    </div>
  </div>

  <h5 class="pt-3">
    Salaries group by designation
  </h5>

  <div class="accordion accordion-flush" id="salaryGroupByDesignation">
    <% @grouped_salaries.each do |designation, salaries| %>

      <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingFor<%= designation %>">
          <button class="accordion-button collapsed bg-secondary text-white" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseFor<%= designation %>" aria-expanded="false" aria-controls="flush-collapseFor<%= designation %>">
            <b><%= Salary.designations[designation] || 'No designation mentioned' %></b> &nbsp;=> <%= salaries.size %> record/s
          </button>
        </h2>

        <div id="flush-collapseFor<%= designation %>" class="accordion-collapse collapse" aria-labelledby="flush-headingFor<%= designation %>" data-bs-parent="#salaryGroupByDesignation">
          <% salaries.sort_by(&:salary_amount_lkr).reverse.each do |salary| %>
            <div class="accordion-body border-bottom"><%= salary.salary_details.html_safe %></div>
          <% end %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/salaries/new.html.erb
<div class="container">

  <p>
    We value your present/past salary submissions here. So everyone can get an idea how much is the salary scale for different technologies in Sri Lanka
  </p>
  <h4>Submit your salary anonymously, we don't tie the salary to you even you are a logged in user.</h4>

  <h5 class="text-warning">Please submit your salary only if you were/are getting this salary while living in Sri Lanka</h5>

  <%= form_with model: @salary, class: 'pt-3 pb-3' do |f| %>
    <div class="row">
      <div class="col-12 col-md-6 pb-3">
        <%= f.label :amount, "Salary amount (Monthly). If your salary is pegged to a foreign currency, submit the amount in foreign currency", class: "required" %>
        <%= f.number_field :amount, required: true, class: "form-control col-4" %>
      </div>

      <div class="col-12 col-md-6 pb-3">
        <%= f.label :currency, "Currency", class: "required" %>
        <%= f.select :currency, Salary.currencies, { include_blank: false }, class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-12 col-md-6 pb-3">
        <%= f.label :year, "Salary received year", class: "required" %>
         <%= f.select :year, ((Date.today.year - 20)..Date.today.year).to_a.reverse, { include_blank: false }, class: "form-control" %>
      </div>

      <div class="col-12 col-md-6 pb-3">
        <%= f.label :work_experience, "Work experience (in years) when receiving the salary", class: "required" %>
        <%= f.select :work_experience, (0..30).to_a, { include_blank: true }, required: true, class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-12 col-md-6 pb-3">
        <%= f.label :education, "Highest educational qualification when receiving the salary"%>
        <%= f.select :education, Salary.educations.map{ |education| [education[1], education[0]] }, { include_blank: true }, class: "form-control" %>
      </div>

      <div class="col-12 col-md-6 pb-3">
        <%= f.label :company_size, "Company employee size when receiving the salary"%>
        <%= f.select :company_size, Salary.company_sizes.map{ |size| [size[1], size[0]] }, { include_blank: true }, class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-12 col-md-6 pb-3">
        <%= f.label :designation, "Designation when receiving the salary(Missing designation? submit an issue in Github)"%>
        <%= f.select :designation, Salary.designations.map{ |designation| [designation[1], designation[0]] }, { include_blank: true }, class: "form-control" %>
      </div>

      <div class="col-12 col-md-6 pb-3">
        <%= f.label :primary_technology, "Primary technology working in the position(Missing technology? submit an issue in Github)"%>
        <%= f.select :primary_technology, Salary.primary_technologies.map{ |technology| [technology[1], technology[0]] }, { include_blank: true }, class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-12 col-md-6 pb-3">
        <%= f.check_box :pegged_salary %>
        <%= f.label :pegged_salary, "Pegged to foreign currency? Yes"%>
      </div>

      <div class="col-12 col-md-6 pb-3 d-block">
        <%= f.check_box :company_base_lk, class: 'd-inline', checked: true %>
        <%= f.label :company_base_lk, "Company has a legal entity in Sri Lanka? Yes", class: 'd-inline' %>
      </div>
    </div>

    <div class="row">
      <div class="col-12 col-md-6 pb-3">
        <%= f.label :advice, "Advice for a junior to achieve your salary or even more"%>
        <%= f.text_area :advice, rows: 5, class: "form-control" %>
      </div>
    </div>

    <div class="row justify-content-center mt-3">
      <div class="col-4 col-md-5">
        <%= f.submit "Add", class: "form-control btn btn-primary" %>
      </div>
    </div>

  <% end %>
</div>