config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    delete 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  scope constraints: ->(req) { MultiTenant::FetchTenant.call(req) == 'tldr' } do
    root to: 'tldr_main#index', as: :tldr_main_root
  end

  scope constraints: ->(req) { MultiTenant::FetchTenant.call(req) == 'peggedplacetowork' } do
    root to: 'pegged_place_to_works#index', as: :peggedplacetowork_root

    get 'great_vs_pegged_place_to_work', to: 'great_place_to_works#index'

    resources :change_requests, only: %i[new create]
  end

  scope constraints: ->(req) { MultiTenant::FetchTenant.call(req) == 'techsalary' } do
    root to: 'salaries#index', as: :techsalary_root

    resources :salaries, only: %i[new create] do
      member do
        post 'vote_accurate'
        post 'vote_fake'
      end

      collection do
        get 'all'
      end
    end
  end

  scope constraints: ->(req) { MultiTenant::FetchTenant.call(req) == 'thetax' } do
    root to: 'thetax#index', as: :thetax_root

    post 'tax_calculate', to: 'thetax#calculate'
  end

  get '*path' => redirect('/') unless Rails.env.development?
end

app/controllers/thetax_controller.rb
# frozen_string_literal: true

class ThetaxController < ApplicationController

  def index
    @tax = Tax.new(
      basic_salary: session[:basic_salary],
      allowance: session[:allowance],
      tax_amount: session[:tax_amount],
      epf: session[:epf],
      etf: session[:etf],
      take_home: session[:take_home]
    )
  end

  def calculate
    calculated_tax = Tax.new(
      basic_salary: params[:tax][:basic_salary].to_i,
      allowance: params[:tax][:allowance].to_i
    ).calculate

    session[:basic_salary] = calculated_tax.basic_salary
    session[:allowance] = calculated_tax.allowance
    session[:tax_amount] = calculated_tax.tax_amount
    session[:epf] = calculated_tax.epf
    session[:etf] = calculated_tax.etf
    session[:take_home] = calculated_tax.take_home

    redirect_to thetax_root_path
  end
end

app/views/thetax/index.html.erb
<div class="container">

  <%= form_with model: @tax, url: tax_calculate_path, :html => {:method => :post}, class: 'pt-3 pb-3' do |f| %>
    <div class="row">
      <div class="col-12 col-md-6 pb-3">
        <%= f.label :basic_salary, "Basic Salary amount (Monthly) in LKR", class: "required" %>
        <%= f.number_field :basic_salary, required: true, class: "form-control col-4" %>
      </div>
    </div>

    <div class="row">
      <div class="col-12 col-md-6 pb-3">
        <%= f.label :allowance, "Allowance amount (Monthly) in LKR" %>
        <%= f.number_field :allowance, class: "form-control col-4" %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-4 col-md-5">
        <%= f.submit "Calculate", class: "form-control btn btn-primary" %>
      </div>
    </div>

    <div class="row mt-4">
      <div class="col-12 col-md-6 pb-3">
        <%= f.label :tax_amount, "Monthly tax amount" %>
        <%= f.number_field :tax_amount, disabled: true, class: "form-control col-4" %>
      </div>
    </div>

    <div class="row mt-4">
      <div class="col-12 col-md-6 pb-3">
        <%= f.label :epf, "Monthly EPF contribution" %>
        <%= f.number_field :epf, disabled: true, class: "form-control col-4" %>
      </div>
    </div>

    <div class="row mt-4">
      <div class="col-12 col-md-6 pb-3">
        <%= f.label :etf, "Monthly ETF contribution" %>
        <%= f.number_field :etf, disabled: true, class: "form-control col-4" %>
      </div>
    </div>

    <div class="row mt-4">
      <div class="col-12 col-md-6 pb-3">
        <%= f.label :take_home, "Monthly take home salary" %>
        <%= f.number_field :take_home, disabled: true, class: "form-control col-4" %>
      </div>
    </div>

  <% end %>

  <p class="col-md-6 mb-0">
    Want to contribute or report an issue?
    <%= link_to 'Check here', "https://github.com/dilumn/tldr", target: '_blank' %>
    <%= link_to image_tag("github-logo.png", width: 30), "https://github.com/dilumn/tldr", target: '_blank' %>
  </p>
  
</div>