config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    delete 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  scope constraints: ->(req) { MultiTenant::FetchTenant.call(req) == 'tldr' } do
    root to: 'tldr_main#index', as: :tldr_main_root
  end

  scope constraints: ->(req) { MultiTenant::FetchTenant.call(req) == 'peggedplacetowork' } do
    root to: 'pegged_place_to_works#index', as: :peggedplacetowork_root

    get 'great_vs_pegged_place_to_work', to: 'great_place_to_works#index'

    resources :change_requests, only: %i[new create]
  end

  scope constraints: ->(req) { MultiTenant::FetchTenant.call(req) == 'techsalary' } do
    root to: 'salaries#index', as: :techsalary_root

    resources :salaries, only: %i[new create] do
      member do
        post 'vote_accurate'
        post 'vote_fake'
      end

      collection do
        get 'all'
      end
    end
  end

  scope constraints: ->(req) { MultiTenant::FetchTenant.call(req) == 'thetax' } do
    root to: 'thetax#index', as: :thetax_root

    post 'tax_calculate', to: 'thetax#calculate'
  end

  get '*path' => redirect('/') unless Rails.env.development?
end

app/views/tech_salaries/index.html.erb
<div class="container">
  <p>
    Need to change any data here? <%= link_to "Submit", new_change_request_path %>
  </p>
  <p>
    Need to add your company to the list? <%= link_to "Submit changes via Github", "https://github.com/dilumn/peggedplacetowork/issues/new", target: '_blank' %>
  </p>

  <hr class="mb-3">

  <%= search_form_for @q, url: techsalary_root_path, class: 'row pb-3' do |f| %>
    <div class="col-4 col-md-2">
      <%= f.select :currency_eq, Salary.currencies.to_a, { include_blank: 'Currency'}, class: "form-control" %>
    </div>
    <div class="col-4 col-md-5">
      <%= f.submit 'Search', class: 'btn btn-primary' %>
    </div>
  <% end %>

  <div class="mb-1 text-end">
    <%= page_entries_info @tech_salaries, entry_name: 'salary' %>
  </div>

  <div class="d-flex mb-1 justify-content-end">
    <%= paginate @tech_salaries %>
  </div>

  <div class="row justify-content-center">
    <div class="col-10 col-md-8 grid-header-col">Salary details</div>
    <div class="col-2 col-md-4 grid-header-col">Accuracy</div>
  </div>

  <% @tech_salaries.each do |salary| %>
    <div class="row justify-content-center">
      <div class="col-10 col-md-8 grid-content-col"><%= salary.amount %></div>
      <div class="col-2 col-md-4 grid-content-col"><%= salary.year %></div>
    </div>
  <% end %>

  <div class="d-flex justify-content-end mt-1">
    <%= paginate @tech_salaries %>
  </div>
</div>